/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdCambiaPassword.java
 *
 * Created on 13/08/2010, 12:27:35 PM
 */
package satelite01;

import BU.Ex.LBU_ClaveCaducoException;
import BU.Ex.LBU_Exception;
import BU.LBU_Seguridad;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author mzavaleta
 */
public class jdCambiaPassword extends javax.swing.JDialog {

    protected String codUsr;
    protected boolean caducoPassword = false;

    /** Creates new form jdCambiaPassword */
    public jdCambiaPassword(java.awt.Frame parent, boolean modal,
            String codUsr,
            boolean caducoPasword) {
        super(parent, modal);
        this.codUsr = codUsr;
        this.caducoPassword=caducoPasword;
        initComponents();
        jtfUser.setText(codUsr);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpfPasw = new javax.swing.JPasswordField();
        jpfPaswNew = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jpfPaswNewR = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jbIngresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambio de Contraseña");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Usuario:");

        jtfUser.setEditable(false);
        jtfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfUserKeyPressed(evt);
            }
        });

        jLabel2.setText("Contraseña Actual:");

        jpfPasw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPaswKeyPressed(evt);
            }
        });

        jpfPaswNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPaswNewKeyPressed(evt);
            }
        });

        jLabel3.setText("Contraseña Nueva:");

        jpfPaswNewR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPaswNewRKeyPressed(evt);
            }
        });

        jLabel4.setText("Repetir contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfPaswNewR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jpfPaswNew, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jtfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jpfPasw, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfPasw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfPaswNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpfPaswNewR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbIngresar.setText("Cambiar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbIngresar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbIngresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpfPasw.grabFocus();
        }
}//GEN-LAST:event_jtfUserKeyPressed

    private void jpfPaswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPaswKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpfPaswNew.grabFocus();
        }
}//GEN-LAST:event_jpfPaswKeyPressed

    private void jpfPaswNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPaswNewKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            jpfPaswNewR.grabFocus();
        }
}//GEN-LAST:event_jpfPaswNewKeyPressed

    private void jpfPaswNewRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPaswNewRKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jbIngresar.grabFocus();
        }
}//GEN-LAST:event_jpfPaswNewRKeyPressed

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        // TODO add your handling code here:
        //A qui se debe validar el login
        try {
            LBU_Seguridad objBU = new LBU_Seguridad();
            String user = jtfUser.getText();
            String pasw = jpfPasw.getText();
            String paswNew = jpfPaswNew.getText();
            String paswNewR = jpfPaswNewR.getText();
            
            if (!paswNew.equals(paswNewR))
                throw new LBU_Exception("La nueva constraseña no coincide con la repeticion");
            if(this.caducoPassword)
            {
                Constantes.UsuarioLogin = objBU.cambiaPasswordCaducado(user,pasw,paswNew);
                Constantes.propiedades.setProperty(Constantes.cPROP_USR_LOG, jtfUser.getText());
            }else
            {
                objBU.cambiaPassword(user, pasw, paswNew);
            }
            JOptionPane.showMessageDialog(this, "Cambio de Contraseña satisfactorio");
            this.setVisible(false);
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getOraMessage());
        } catch (LBU_ClaveCaducoException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}//GEN-LAST:event_jbIngresarActionPerformed
    private boolean cancelar=false;
    public boolean esCancelar()
    {
        return cancelar;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.cancelar = true;
        this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.cancelar = true;
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JPasswordField jpfPasw;
    private javax.swing.JPasswordField jpfPaswNew;
    private javax.swing.JPasswordField jpfPaswNewR;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
