/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdMttoConsulta.java
 *
 * Created on 12/08/2010, 05:52:33 PM
 */
package satelite01;

import BE.Ex.LBE_Exception;
import BE.LBE_BDatos;
import BE.LBE_Consulta;
import BE.LBE_Grupo;
import BU.Ex.LBU_Exception;
import BU.LBU_BDatos;
import BU.LBU_Consulta;
import BU.LBU_Grupo;

import java.sql.ResultSet;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mzavaleta
 */
public class jdMttoConsulta extends javax.swing.JDialog {

    /** Creates new form jdMttoConsulta */
    private boolean cancelar = true;
    private int codigo;
    private int idGrupo;

    public boolean isCancelar() {
        return cancelar;
    }
    public jdMttoConsulta(java.awt.Frame parent, boolean modal, int codigo, int idGrupo) {
        super(parent, modal);
        initComponents();
     
        this.idGrupo= idGrupo;
        this.codigo = codigo;
        try {
            LBE_Consulta consulta = null;
            if (codigo != 0) {
                consulta = cargaDatos();
            }
            cargaBDatos(consulta);
            cargaGrupos(consulta);
        } catch (LBU_Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    public jdMttoConsulta(java.awt.Frame parent, boolean modal, int codigo) {
        super(parent, modal);
        initComponents();
        this.codigo = codigo;
        try {
            LBE_Consulta consulta = null;
            if (codigo != 0) {
                consulta = cargaDatos();
            }
            cargaBDatos(consulta);
            cargaGrupos(consulta);
        } catch (LBU_Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jbValidar = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jbOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbBDatos = new javax.swing.JComboBox();
        jcbGrupos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsulta = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Mantenimiento de Consulta");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/report.png"))); // NOI18N
        jbValidar.setToolTipText("Validar");
        jbValidar.setFocusable(false);
        jbValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbValidar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbValidar);

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/report_disk.png"))); // NOI18N
        jbSave.setToolTipText("Guardar");
        jbSave.setFocusable(false);
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jbSave);

        jbOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/door_out.png"))); // NOI18N
        jbOut.setToolTipText("Cerrar");
        jbOut.setFocusable(false);
        jbOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOutActionPerformed(evt);
            }
        });
        jToolBar1.add(jbOut);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Base de Datos");

        jtfTitulo.setToolTipText("Nombre de la Consulta");

        jLabel2.setText("Titulo");

        jLabel4.setText("Grupo");

        jcbBDatos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBDatosActionPerformed(evt);
            }
        });

        jcbGrupos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGrupos.setEnabled(false);

        jLabel5.setText("Id. Opc Seguridad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(22, 22, 22))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(62, 62, 62)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbGrupos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbBDatos, javax.swing.GroupLayout.Alignment.LEADING, 0, 420, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Consulta:");

        jtaConsulta.setColumns(20);
        jtaConsulta.setFont(new java.awt.Font("Courier New", 0, 12));
        jtaConsulta.setRows(5);
        jScrollPane1.setViewportView(jtaConsulta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(597, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
}//GEN-LAST:event_jbOutActionPerformed

    private void jcbBDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBDatosActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        try {
            // TODO add your handling code here:
            jSpinner1.commitEdit();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en formato de Id de Opción de Seguridad");
            return;
        }
        LBE_Consulta elem = new LBE_Consulta();
        elem.setTitulo(jtfTitulo.getText());
        elem.setIdOpcionSegur((Integer)jSpinner1.getValue());
        elem.setBe_BDatos((LBE_BDatos) jcbBDatos.getSelectedItem());
        elem.setGrupo((LBE_Grupo) jcbGrupos.getSelectedItem());
        elem.setQuery(jtaConsulta.getText());

        try
        {
            LBU_Consulta objBU = new LBU_Consulta(Constantes.UsuarioLogin.getBDatos());
            if (this.codigo > 0) {
                elem.setId(this.codigo);
                objBU.save(elem, Constantes.UsuarioLogin.getUsrLogin());
            } else {
                objBU.add(elem, Constantes.UsuarioLogin.getUsrLogin());
            }
        }catch(LBU_Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, 
                    "Error al crear/guardar consulta:" + ex.getMessage());
            return;
        }
        cancelar = false;
        setVisible(false);
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidarActionPerformed
        // TODO add your handling code here:

        LBE_Consulta consulta = new LBE_Consulta();
        consulta.setBe_BDatos((LBE_BDatos) jcbBDatos.getSelectedItem());
        consulta.setQuery(jtaConsulta.getText());
        String query = consulta.getQuery();
        try {
            ArrayList<String> params = consulta.parametros();
            if (params.size() > 0) {
                jdParametros frmParametros =
                        new jdParametros(
                        null,
                        true,
                        params,
                        consulta.getId());
                frmParametros.setLocationRelativeTo(this);
                frmParametros.setVisible(true);
                if (!frmParametros.isCancelado()) {
                    JOptionPane.showMessageDialog(null, "Consulta cancelada");
                    return;
                }
                DefaultTableModel model = frmParametros.getModel();
                for (int ix = 0; ix < model.getRowCount(); ix++) {
                    String nomParam = (String) model.getValueAt(ix, 0);
                    String valParam = (String) model.getValueAt(ix, 1);
                    query = query.replace("@" + nomParam + "@", valParam);
                    Constantes.propiedades.setProperty("param." + nomParam, valParam);
                }
                frmParametros.dispose();
            }
            LBU_Consulta objBU = new LBU_Consulta(Constantes.UsuarioLogin.getBDatos());
            ResultSet rs = objBU.ejecutar(consulta, query, "Test", true);

            JOptionPane.showMessageDialog(null, "Test OK");

        } catch (LBE_Exception ex) {
            JOptionPane.showMessageDialog(null, "Error:" + ex.getMessage());
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(null, "Error:" + ex.getMessage());
        }
    }//GEN-LAST:event_jbValidarActionPerformed

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    private void cargaBDatos(LBE_Consulta consulta) throws LBU_Exception {
        DefaultComboBoxModel model = (DefaultComboBoxModel) jcbBDatos.getModel();
        model.removeAllElements();
        LBU_BDatos objBU = new LBU_BDatos(Constantes.UsuarioLogin.getBDatos());
        for (LBE_BDatos elem : objBU.getAll()) {
            model.addElement(elem);
            if (consulta != null) {
                if (elem.getCodigo() == consulta.getBe_BDatos().getCodigo()) {
                    model.setSelectedItem(elem);
                }
            }
        }
    }

    private void cargaGrupos(LBE_Consulta consulta) throws LBU_Exception {
        DefaultComboBoxModel model = (DefaultComboBoxModel) jcbGrupos.getModel();
        model.removeAllElements();
        LBU_Grupo objBU = new LBU_Grupo(Constantes.UsuarioLogin.getBDatos());
        for (LBE_Grupo elem : objBU.getAll()) {
            model.addElement(elem);
            if (consulta != null) {
                if (elem.getId() == consulta.getGrupo().getId()) {
                    model.setSelectedItem(elem);
                }
            }else
            {
                if (elem.getId() == this.idGrupo) {
                    model.setSelectedItem(elem);
                }
            }
        }
    }

    private LBE_Consulta cargaDatos() throws LBU_Exception {
        LBU_Consulta objBU = new LBU_Consulta(Constantes.UsuarioLogin.getBDatos());
        LBE_Consulta consulta = objBU.get(codigo);
        jtfTitulo.setText(consulta.getTitulo());
        jSpinner1.setValue(consulta.getIdOpcionSegur());
        jtaConsulta.setText(consulta.getQuery());
        return consulta;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbOut;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbValidar;
    private javax.swing.JComboBox jcbBDatos;
    private javax.swing.JComboBox jcbGrupos;
    private javax.swing.JTextArea jtaConsulta;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
