/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdMttoGrupo.java
 *
 * Created on 19/08/2010, 12:02:14 PM
 */
package satelite01;


import BE.LBE_Grupo;
import BU.Ex.LBU_Exception;
import BU.LBU_Grupo;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author mzavaleta
 */
public class jdMttoGrupo extends javax.swing.JDialog {

    /** Creates new form jdMttoGrupo */
    private int id;
    private boolean  cancelar=true;

    public boolean isCancelar() {
        return cancelar;
    }


    public jdMttoGrupo(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.id = id;
        try {
            if (id != 0) {
                cargaDatos();
            }
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar grupo:" +ex.getMessage(),
                    "Error",JOptionPane.WARNING_MESSAGE);
        }

    }

    private void cargaDatos() throws LBU_Exception {
        LBU_Grupo objBU = new LBU_Grupo(Constantes.UsuarioLogin.getBDatos());
        LBE_Grupo elem = objBU.get(id);
        jtfNombre.setText(elem.getNombre());
        jSpinner1.setValue(elem.getIdOpcionSegur());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbSave = new javax.swing.JButton();
        jbOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtfNombre = new javax.swing.JTextField(35);
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setTitle("Mantenimiento de grupo");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/save.gif"))); // NOI18N
        jbSave.setToolTipText("Guardar");
        jbSave.setFocusable(false);
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jbSave);

        jbOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/door_out.png"))); // NOI18N
        jbOut.setToolTipText("Cerrar");
        jbOut.setFocusable(false);
        jbOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOutActionPerformed(evt);
            }
        });
        jToolBar1.add(jbOut);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Nombre");

        jLabel5.setText("Id. Opc Seguridad");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));
        jSpinner1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOutActionPerformed
        // TODO add your handling code here:
       setVisible(false);
}//GEN-LAST:event_jbOutActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        try {
            validaDatos();
            LBU_Grupo objBU = new LBU_Grupo(Constantes.UsuarioLogin.getBDatos());

            LBE_Grupo elem = new LBE_Grupo();
            elem.setId(id);
            elem.setNombre(jtfNombre.getText());
            elem.setIdOpcionSegur((Integer) jSpinner1.getValue());
            if (this.id == 0) {
                //Crea el grupo
                objBU.add(elem, Constantes.UsuarioLogin.getUsrLogin());
            } else {
                //Guarda el grupo
                objBU.save(elem, Constantes.UsuarioLogin.getUsrLogin());
            }
            cancelar=false;
            setVisible(false);

        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear/guardar grupo: "
                    + ex.getMessage(), "Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jSpinner1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner1FocusLost
    }//GEN-LAST:event_jSpinner1FocusLost
    private void validaDatos() throws LBU_Exception {
        try {
            //jSpinner1.getModel().;
            jSpinner1.commitEdit();
            jtfNombre.grabFocus();
            if (jtfNombre.getText().trim().equals("")) {
                throw new LBU_Exception("Debe ingresar un valor para el nombre del grupo");
            }
            if (jtfNombre.getText().length() > 35) {
                throw new LBU_Exception("Tamaño de nombre no debe exceder los 35 caractéres");
            }
            Integer tagOpcSeg = (Integer) jSpinner1.getValue();
            if (tagOpcSeg <= 0) {
                throw new LBU_Exception("Codigo de Opción de Seguridad debe ser mayor a 0");
            }
        } catch (ParseException ex) {
            throw new LBU_Exception("Código de Opción de Seguridad incorrecto");
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbOut;
    private javax.swing.JButton jbSave;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
