/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdMttoBDatos.java
 *
 * Created on 19/08/2010, 02:52:33 PM
 */
package satelite01;

import BE.LBE_BDatos;
import BE.LBE_Driver;
import BU.Ex.LBU_Exception;
import BU.LBU_BDatos;
import BU.LBU_Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author mzavaleta
 */
public class jdMttoBDatos extends javax.swing.JDialog {

    /** Creates new form jdMttoBDatos */
    private int codigo;
    private boolean cancelar=true;

    public boolean isCancelar() {
        return cancelar;
    }

    public jdMttoBDatos(java.awt.Frame parent, boolean modal, int codigo) {
        super(parent, modal);
        initComponents();
        jcbDriver.removeAllItems();
        this.codigo = codigo;
        LBE_BDatos bDatos = null;
        try {
            if (codigo != 0) {
                bDatos = cargaDatos(this.codigo);
            }
            int codigoDriver = 0;
            if (bDatos != null) {
                codigoDriver = bDatos.getDriver().getCodigo();
            }
            cargaDrivers(codigoDriver);
        } catch (LBU_Exception ex) {
            System.err.println(ex);
        }
    }

    private LBE_BDatos cargaDatos(int codigo) throws LBU_Exception {
        LBU_BDatos objBU = new LBU_BDatos(Constantes.UsuarioLogin.getBDatos());
        LBE_BDatos elem = objBU.get(codigo);
        jtfNombre.setText(elem.getNombre());
        jtfUrl.setText(elem.getUrl());
        jtfUsuario.setText(elem.getUsuario());
        jpfClave.setText(elem.getClave());
        return elem;
    }

    private void cargaDrivers(int codigoDriver) throws LBU_Exception {
        LBU_Driver objBU = new LBU_Driver(Constantes.UsuarioLogin.getBDatos());
        for (LBE_Driver elem : objBU.getAll()) {
            jcbDriver.addItem(elem);
            if (elem.getCodigo() == codigoDriver) {
                jcbDriver.setSelectedItem(elem);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbTest = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jbOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtfNombre = new javax.swing.JTextField(35);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbDriver = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtfUrl = new javax.swing.JTextField(35);
        jLabel5 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField(35);
        jLabel6 = new javax.swing.JLabel();
        jpfClave = new javax.swing.JPasswordField();

        setTitle("Mantenimiento de Base de Datos");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/database_connect.png"))); // NOI18N
        jbTest.setToolTipText("Testear coneccion");
        jbTest.setFocusable(false);
        jbTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTestActionPerformed(evt);
            }
        });
        jToolBar1.add(jbTest);

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/database_save.png"))); // NOI18N
        jbSave.setToolTipText("Guardar");
        jbSave.setFocusable(false);
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jbSave);

        jbOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/door_out.png"))); // NOI18N
        jbOut.setToolTipText("Cerrar");
        jbOut.setFocusable(false);
        jbOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOutActionPerformed(evt);
            }
        });
        jToolBar1.add(jbOut);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Driver:");

        jcbDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDriverActionPerformed(evt);
            }
        });

        jLabel4.setText("URL:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Clave:");

        jpfClave.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jtfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(442, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jpfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        try {
            LBU_BDatos objBU = new LBU_BDatos(Constantes.UsuarioLogin.getBDatos());
            LBE_BDatos bDatos = new LBE_BDatos();
            LBE_Driver driver = (LBE_Driver) jcbDriver.getSelectedItem();
            bDatos.setNombre(jtfNombre.getText());
            bDatos.setDriver(driver);
            bDatos.setUrl(jtfUrl.getText());
            bDatos.setUsuario(jtfUsuario.getText());
            bDatos.setClave(jpfClave.getText());
            if (this.codigo == 0) {
                objBU.add(bDatos, Constantes.UsuarioLogin.getUsrLogin());
            } else {
                bDatos.setCodigo(this.codigo);
                objBU.save(bDatos, Constantes.UsuarioLogin.getUsrLogin());
            }
            cancelar=false;
            this.setVisible(false);
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear/guardar Base de Datos: "
                    + ex.getMessage(), "Guardar/Crear", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jbSaveActionPerformed

    private void jbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jbOutActionPerformed
    private void testConnection(LBE_BDatos bDatos) throws LBU_Exception {
        try {
            Class.forName(bDatos.getDriver().getDriver());
            Connection cn = DriverManager.getConnection(bDatos.getUrl(),
                    bDatos.getUsuario(), bDatos.getClave());
            cn.close();
        } catch (ClassNotFoundException ex) {
            throw new LBU_Exception("Driver: " + bDatos.getDriver().getDriver() + " no encontrado");
        } catch (SQLException ex) {
            throw new LBU_Exception("Error al conectar a Base de datos "
                    + bDatos.getUrl() + "\n" + ex.getMessage());
        }
    }
    private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
        // TODO add your handling code here:
        LBE_BDatos bDatos = new LBE_BDatos();
        LBE_Driver driver = (LBE_Driver) jcbDriver.getSelectedItem();
        bDatos.setDriver(driver);
        bDatos.setUrl(jtfUrl.getText());
        bDatos.setUsuario(jtfUsuario.getText());
        bDatos.setClave(jpfClave.getText());
        try {
            testConnection(bDatos);
            JOptionPane.showMessageDialog(rootPane, "Test satisfactorio",
                    "Test", JOptionPane.INFORMATION_MESSAGE);
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                    "Test", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbTestActionPerformed

    private void jcbDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDriverActionPerformed
        // TODO add your handling code here:
        //System.out.println(evt);
        JComboBox jcombo = (JComboBox) evt.getSource();
        LBE_Driver driver = (LBE_Driver) jcombo.getSelectedItem();
        if (driver!=null && this.codigo==0)
            jtfUrl.setText(driver.getUrl());
    }//GEN-LAST:event_jcbDriverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbOut;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbTest;
    private javax.swing.JComboBox jcbDriver;
    private javax.swing.JPasswordField jpfClave;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUrl;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
