/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdParametros.java
 *
 * Created on 02/08/2010, 04:18:19 PM
 */

package satelite01;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mzavaleta
 */
public class jdParametros extends javax.swing.JDialog {

    /** Creates new form jdParametros */
    private int idQuery;
    protected ArrayList<String> params;
    public DefaultTableModel getModel()
    {
        return (DefaultTableModel) jTable1.getModel();
    }

    public jdParametros(Frame parent, boolean modal,
            ArrayList<String> params, int idQuery) {
        super(parent, modal);
        initComponents();
        this.params = params;
        this.idQuery= idQuery;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(String param:params)
        {
            String [] datos= {param,Constantes.propiedades.getProperty("param."+param,""),"...", "..."};
            model.addRow(datos);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametros");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parametro", "Valor", "Selecc.", "Varios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    protected boolean cancelado=false;

    public boolean isCancelado() {
        return cancelado;
    }

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        cancelado=false;
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // TODO add your handling code here:
        cancelado=true;
        if(jTable1.isEditing())
            jTable1.getCellEditor().stopCellEditing();
        this.setVisible(false);
    }//GEN-LAST:event_jbOKActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 1) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            int col = target.getSelectedColumn();
            if (col==2)
            {
                String nomParam =(String) jTable1.getValueAt(row, 0);
                String valParam =(String) jTable1.getValueAt(row, 1);
                jdParCbo Lista = new jdParCbo(null, true, this.idQuery,nomParam,valParam);
                Lista.setLocationRelativeTo(this);
                Lista.setVisible(true);
                if (!Lista.isCancelado())
                {
                    target.setValueAt(Lista.getValParam(), row, 1);
                }
            }
            if (col==3)
            {
                //String nomParam =(String) jTable1.getValueAt(row, 0);
                //String valParam =(String) jTable1.getValueAt(row, 1);
                jdParamVarios Lista = new jdParamVarios(null, true);
                Lista.setValParam( (String)jTable1.getValueAt(row, 1));
                Lista.setLocationRelativeTo(this);
                Lista.setVisible(true);
                if (!Lista.isCancelado())
                {
                    target.setValueAt(Lista.getValParam(), row, 1);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    // End of variables declaration//GEN-END:variables

}
