/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdParCbo.java
 *
 * Created on 17/09/2010, 04:34:01 PM
 */
package satelite01;

import BE.LBE_Parametro;
import BE.LBE_ParametroValor;
import BU.Ex.LBU_Exception;
import BU.LBU_Parametro;
import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logger.Log;

/**
 *
 * @author mzavaleta
 */
public class jdParCbo extends javax.swing.JDialog {

    private int idQuery;
    private String nomParam;
    private String valParam;

    public String getValParam() {
        return valParam;
    }

    public void setValParam(String valParam) {
        this.valParam = valParam;
    }

    /**
     * Creates new form jdParCbo
     */
    public jdParCbo(Frame parent,
            boolean modal,
            int idQuery,
            String nomParam,
            String valParam) {
        super(parent, modal);
        initComponents();
        this.idQuery = idQuery;
        this.nomParam = nomParam;
        this.valParam = valParam;
        try {
            cargaDatos();
        } catch (LBU_Exception ex) {
            Log.error("Error al leer lista de parámetros", ex);
            JOptionPane.showMessageDialog(null, "Error al leer lista de parámetros");
        }
    }
    private ArrayList<LBE_ParametroValor[]> elementos = new ArrayList<LBE_ParametroValor[]>();

    private void cargaDatos() throws LBU_Exception {
        LBU_Parametro buParam = new LBU_Parametro(Constantes.UsuarioLogin.getBDatos());
        LBE_Parametro parametro = buParam.getListaValores(idQuery, nomParam);
        if (parametro == null) {
            this.cancelado = true;
            this.setVisible(false);
            return;
        }
        ResultSet rs = parametro.getResultSet();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int numRowSel = -1;
        int i = 0;
        try {
            rs.setFetchSize(10000);
            while (rs.next()) {
                LBE_ParametroValor paramValor = new LBE_ParametroValor();
                LBE_ParametroValor[] datos = {paramValor};
                elementos.add(datos);
                paramValor.setValor(rs.getString(1));
                paramValor.setDescripcion(rs.getString(2));
                if (paramValor.getValor().trim().equalsIgnoreCase(valParam)) {
                    numRowSel = i;
                }
                i++;
                model.addRow(datos);
            }
        } catch (SQLException ex) {
            Log.error("Error al leer lista de parámetros", ex);
            throw new LBU_Exception("Error al leer lista de parametros");
        } catch (NullPointerException ex) {
            Log.error("Error al leer lista de parámetros", ex);
            throw new LBU_Exception("Error al leer lista de parametros");
        }
        if (numRowSel != -1) {
            jTable1.setRowSelectionInterval(numRowSel, numRowSel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Parametros");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancel)
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean cancelado = false;
    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // TODO add your handling code here:
        cancelado = false;
        if (jTable1.isEditing()) {
            jTable1.getCellEditor().stopCellEditing();
        }
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            LBE_ParametroValor paramValor = (LBE_ParametroValor) jTable1.getValueAt(row, 0);
            this.valParam = paramValor.getValor().trim();
        }
        this.setVisible(false);
}//GEN-LAST:event_jbOKActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        cancelado = true;
        this.setVisible(false);
}//GEN-LAST:event_jbCancelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            cancelado = false;
            if (jTable1.isEditing()) {
                jTable1.getCellEditor().stopCellEditing();
            }
            int row = jTable1.getSelectedRow();
            LBE_ParametroValor paramValor = (LBE_ParametroValor) jTable1.getValueAt(row, 0);
            this.valParam = paramValor.getValor().trim();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int numRowSel = -1;
        int i = 0;
        try {
            if (!jtfBuscar.getText().trim().equals("")) {
                model.setNumRows(0);
                for (LBE_ParametroValor[] elem : elementos) {
                    if (elem[0].getDescripcion().toUpperCase().startsWith(jtfBuscar.getText().toUpperCase())) {
                        if (elem[0].getValor().trim().equalsIgnoreCase(valParam)) {
                            numRowSel = i;
                        }
                        i++;
                        model.addRow(elem);
                    }
                }
            } else {
                model.setNumRows(0);
                for (LBE_ParametroValor[] elem : elementos) {
                    if (elem[0].getValor().trim().equalsIgnoreCase(valParam)) {
                        numRowSel = i;
                    }
                    i++;
                    model.addRow(elem);
                }
            }
        } catch (NullPointerException ex) {
            Log.error("Error al leer lista de parámetros", ex);
            //throw new BU_Exception("Error al leer lista de parametros");
        }
        if (numRowSel != -1) {
            jTable1.setRowSelectionInterval(numRowSel, numRowSel);
        }
    }//GEN-LAST:event_jtfBuscarKeyReleased
    public boolean isCancelado() {
        return cancelado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
