/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfLogin.java
 *
 * Created on 09/08/2010, 10:41:27 AM
 */
package satelite01;

import BU.Ex.LBU_ClaveCaducoException;
import BU.Ex.LBU_Exception;
import BU.LBU_Seguridad;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import logger.Log;

/**
 *
 * @author mzavaleta
 */
public class jfLogin extends javax.swing.JDialog implements PropertyChangeListener {

    protected MdiMain mdiMain;

    /**
     * Creates new form jfLogin
     */
    public jfLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        mdiMain = (MdiMain) parent;
        initComponents();
        jProgressBar1.setVisible(false);
        String usrLog = Constantes.propiedades.getProperty(Constantes.cPROP_USR_LOG, "");
        jtfUser.setText(usrLog);
        if (!usrLog.equals("")) {
            jpfPasw.grabFocus();
        }
        task = new Task(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jpfPasw = new javax.swing.JPasswordField();
        jbIngresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setModal(true);
        setName("Login"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jtfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfUserKeyPressed(evt);
            }
        });

        jpfPasw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPaswKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jpfPasw, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfPasw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jbIngresar)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jbIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (task.getState() == SwingWorker.StateValue.STARTED) {
            try {
                task.cancel(true);
                task.get();
            } catch (InterruptedException exp) {
                System.err.print(exp);
            } catch (java.util.concurrent.ExecutionException exp) {
                System.err.print(exp);
            } catch (java.util.concurrent.CancellationException exp) {
                System.err.print(exp);
            }

        }
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    Task task = new Task(this);
    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        task = new Task(this);
        jbIngresar.setEnabled(false);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        task.addPropertyChangeListener(this);
        Log.debug("Lazamos tarea o hilo de Login");
        task.execute();
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void jtfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpfPasw.grabFocus();
        }
    }//GEN-LAST:event_jtfUserKeyPressed

    private void jpfPaswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPaswKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbIngresar.grabFocus();
        }
    }//GEN-LAST:event_jpfPaswKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //task.cancel(false);
        task.cancel(true);
        System.exit(0);


    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JPasswordField jpfPasw;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables

    class Task extends SwingWorker<Void, Void> {
        /*
         * Main task. Executed in background thread.
         */

        jfLogin frame;

        public Task(jfLogin frame) {
            this.frame = frame;
        }

        @Override
        public Void doInBackground() {
            jProgressBar1.setVisible(true);
            setProgress(1);
            try {
                LBU_Seguridad objBU = new LBU_Seguridad();
                String user = jtfUser.getText();
                char[] paswC = jpfPasw.getPassword();
                StringBuilder sbPasw = new StringBuilder();
                for (int ix = 0; ix < paswC.length; ix++) {
                    sbPasw.append(paswC[ix]);
                }
                jbIngresar.setEnabled(false);
                jtfUser.setEnabled(false);
                jpfPasw.setEnabled(false);
                Log.debug("Validacion de Login");
                Constantes.UsuarioLogin = objBU.login(user, sbPasw.toString());
                Log.debug("Login Ok");
                Constantes.propiedades.setProperty(Constantes.cPROP_USR_LOG, jtfUser.getText());
                jProgressBar1.setVisible(false);
                this.frame.dispose();
            } catch (LBU_Exception ex) {
                Log.debug("Error de login: " + ex.getMessage());
                JOptionPane.showMessageDialog(this.frame, ex.getOraMessage());
                //JOptionPane.showMessageDialog(this.frame, ex.getMessage());
                jbIngresar.setEnabled(true);
                jtfUser.setEnabled(true);
                jpfPasw.setEnabled(true);
            } catch (LBU_ClaveCaducoException ex) {
                Log.debug("Error de login: " + ex.getMessage());
                jProgressBar1.setVisible(false);
                jdCambiaPassword fCP = new jdCambiaPassword(mdiMain, true, jtfUser.getText(), true);
                fCP.setLocationRelativeTo(mdiMain);
                fCP.setVisible(true);
                if (!fCP.esCancelar()) {
                    this.frame.setVisible(false);
                } else {
                    jbIngresar.setEnabled(true);
                    jtfUser.setEnabled(true);
                    jpfPasw.setEnabled(true);
                }
            } catch (Exception ex) {
                Log.error("Error en login: " + ex.getMessage(),ex );
            }
            setProgress(100);

            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            //Toolkit.getDefaultToolkit().beep();
            jbIngresar.setEnabled(true);
            setCursor(null);
            jProgressBar1.setIndeterminate(false);
            jProgressBar1.setString("");
            jProgressBar1.setVisible(false);
        }
    }

    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress".equals(evt.getPropertyName())) {
            jProgressBar1.setIndeterminate(true);
            jProgressBar1.setString("Validando Usuario");
        }
    }
}
