/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifBaseDatos.java
 *
 * Created on 18/08/2010, 02:30:31 PM
 */
package satelite01;

import BE.LBE_BDatos;
import BU.Ex.LBU_Exception;
import BU.LBU_BDatos;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import logger.Log;

/**
 *
 * @author mzavaleta
 */
public class jifBaseDatosAll extends javax.swing.JInternalFrame {

    /** Creates new form jifBaseDatos */
    public jifBaseDatosAll() {
        initComponents();
        DefaultTableColumnModel model = (DefaultTableColumnModel) jTable1.getColumnModel();
        model.getColumn(0).setPreferredWidth(50);
        model.getColumn(1).setPreferredWidth(300);
        model.getColumn(2).setPreferredWidth(300);
        model.getColumn(3).setPreferredWidth(130);
        model.getColumn(4).setPreferredWidth(200);
        cargar();
    }

    private void cargar() {
        LBU_BDatos objBU;
        try {
            objBU = new LBU_BDatos(Constantes.UsuarioLogin.getBDatos());
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            //model.getDataVector().removeAllElements();
            int numRows = model.getRowCount();
            for (int i = numRows - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            for (LBE_BDatos elem : objBU.getAll()) {
                Vector row = new Vector();
                row.add(elem.getCodigo());
                row.add(elem.getNombre());
                row.add(elem.getUrl());
                row.add(elem.getUsuario());
                row.add(elem.getDriver().getNombre());
                model.addRow(row);
            }
        } catch (LBU_Exception ex) {
            Log.error("Error al cargar lista de Base de Datos", ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbRefresh = new javax.swing.JButton();
        jbNew = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbtExit = new javax.swing.JButton();
        jlMensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenedor de Base de Datos");
        setAutoscrolls(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/database_refresh.png"))); // NOI18N
        jbRefresh.setToolTipText("Recargar");
        jbRefresh.setFocusable(false);
        jbRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(jbRefresh);

        jbNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/database_add.png"))); // NOI18N
        jbNew.setToolTipText("Crear Base de Datos");
        jbNew.setFocusable(false);
        jbNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });
        jToolBar1.add(jbNew);

        jbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/database_edit.png"))); // NOI18N
        jbEdit.setToolTipText("Editar Base de Datos");
        jbEdit.setFocusable(false);
        jbEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        jToolBar1.add(jbEdit);

        jbtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/door_out.png"))); // NOI18N
        jbtExit.setToolTipText("Cerrar");
        jbtExit.setFocusable(false);
        jbtExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtExit);

        jlMensaje.setText("  ");
        jToolBar1.add(jlMensaje);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Url", "Usuario", "Driver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(111);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_jbtExitActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void editar()
    {
        int numRow = jTable1.getSelectedRow();
        if(numRow>-1)
        {
            Integer id = (Integer) jTable1.getValueAt(numRow, 0);
            jdMttoBDatos mttoBD = new jdMttoBDatos(null, true, id);
            mttoBD.setLocationRelativeTo(this);
            mttoBD.setVisible(true);
            if(!mttoBD.isCancelar())
                cargar();
        }else
        {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe seleccionar una registro","Base de Datos",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            editar();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        // TODO add your handling code here:
        jdMttoBDatos mttoBD = new jdMttoBDatos(null, true, 0);
        mttoBD.setLocationRelativeTo(this);
        mttoBD.setVisible(true);
        if (!mttoBD.isCancelar())
            cargar();
    }//GEN-LAST:event_jbNewActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_jbEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbtExit;
    private javax.swing.JLabel jlMensaje;
    // End of variables declaration//GEN-END:variables
}
