package satelite01;


import BE.LBE_Consulta;
import BE.LBE_Grupo;
import BU.Ex.LBU_Exception;
import BU.LBU_Grupo;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifConsultasAll.java
 *
 * Created on 19/08/2010, 05:22:40 PM
 */
/**
 *
 * @author mzavaleta
 */
public class jifConsultasAll extends javax.swing.JInternalFrame {

    DefaultMutableTreeNode root;

    /** Creates new form jifConsultasAll */
    public jifConsultasAll() {
        initComponents();
        root = new DefaultMutableTreeNode("Grupos");
        DefaultTreeModel treeModel = new DefaultTreeModel(root);
        jTree1.setModel(treeModel);
        int dividerLocation = Integer.parseInt(Constantes.propiedades.getProperty(Constantes.cPROP_WITH_PAN_LEFT_BD, "0"));
        if (dividerLocation > 0) {
            jSplitPane1.setDividerLocation(dividerLocation);
        }
        DefaultTableColumnModel model = (DefaultTableColumnModel) jTable1.getColumnModel();
        model.getColumn(0).setPreferredWidth(50);
        model.getColumn(1).setPreferredWidth(300);
        model.getColumn(2).setPreferredWidth(300);
        cargaGrupos();
    }

    private void cargaGrupos(DefaultMutableTreeNode root) throws LBU_Exception {
        jbEditGrup.setEnabled(false);
        //jpMain.set;
        root.removeAllChildren();
        DefaultTreeModel treeModel = (DefaultTreeModel) jTree1.getModel();
        LBU_Grupo objBUS = new LBU_Grupo(Constantes.UsuarioLogin.getBDatos());
        ArrayList<LBE_Grupo> grupos = objBUS.getAll();
        for (LBE_Grupo grupo : grupos) {
            DefaultMutableTreeNode nodeGrupo = new DefaultMutableTreeNode(grupo);
            root.add(nodeGrupo);
        }
        treeModel.reload();
        cargaBDatos();
    }

    private void cargaGrupos() {
        try {
            cargaGrupos(root);
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar datos: "
                    + ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jpMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jbRefreshConsultas = new javax.swing.JButton();
        jbNewConsulta = new javax.swing.JButton();
        jbEditConsulta = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jbRefresh = new javax.swing.JButton();
        jbNew = new javax.swing.JButton();
        jbEditGrup = new javax.swing.JButton();
        jbtExit = new javax.swing.JButton();
        jlMensaje = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento de Consultas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane1ComponentResized(evt);
            }
        });

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Base de Datos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jbRefreshConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/arrow_refresh.png"))); // NOI18N
        jbRefreshConsultas.setToolTipText("Recargar consultas");
        jbRefreshConsultas.setEnabled(false);
        jbRefreshConsultas.setFocusable(false);
        jbRefreshConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRefreshConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbRefreshConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshConsultasActionPerformed(evt);
            }
        });
        jToolBar2.add(jbRefreshConsultas);

        jbNewConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/report_add.png"))); // NOI18N
        jbNewConsulta.setToolTipText("Crear consulta");
        jbNewConsulta.setEnabled(false);
        jbNewConsulta.setFocusable(false);
        jbNewConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNewConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNewConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewConsultaActionPerformed(evt);
            }
        });
        jToolBar2.add(jbNewConsulta);

        jbEditConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/report_edit.png"))); // NOI18N
        jbEditConsulta.setToolTipText("Editar consulta");
        jbEditConsulta.setEnabled(false);
        jbEditConsulta.setFocusable(false);
        jbEditConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbEditConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditConsultaActionPerformed(evt);
            }
        });
        jToolBar2.add(jbEditConsulta);

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jpMain);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/arrow_refresh.png"))); // NOI18N
        jbRefresh.setToolTipText("Recargar grupos");
        jbRefresh.setFocusable(false);
        jbRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(jbRefresh);

        jbNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/world_add.png"))); // NOI18N
        jbNew.setToolTipText("Crear grupo");
        jbNew.setFocusable(false);
        jbNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });
        jToolBar1.add(jbNew);

        jbEditGrup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/world_edit.png"))); // NOI18N
        jbEditGrup.setToolTipText("Editar grupo");
        jbEditGrup.setFocusable(false);
        jbEditGrup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditGrup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbEditGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditGrupActionPerformed(evt);
            }
        });
        jToolBar1.add(jbEditGrup);

        jbtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/satelite01/icons/door_out.png"))); // NOI18N
        jbtExit.setToolTipText("Cerrar");
        jbtExit.setFocusable(false);
        jbtExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtExit);

        jlMensaje.setText("  ");
        jToolBar1.add(jlMensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jbtExitActionPerformed

    private void salir() {
        int widthPan = jSplitPane1.getDividerLocation();
        Constantes.propiedades.setProperty(Constantes.cPROP_WITH_PAN_LEFT_BD,
                String.valueOf(widthPan));
        this.dispose();
    }
    private void jSplitPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jSplitPane1ComponentResized

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        salir();

    }//GEN-LAST:event_formInternalFrameClosing

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        jdMttoGrupo frmGrupo = new jdMttoGrupo(null, true, 0);
        frmGrupo.setLocationRelativeTo(this);
        frmGrupo.setVisible(true);
        if (!frmGrupo.isCancelar()) {
            cargaGrupos();
        }
    }//GEN-LAST:event_jbNewActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
        cargaGrupos();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
        TreePath selPath = evt.getPath();
        DefaultMutableTreeNode nodeSel = (DefaultMutableTreeNode) selPath.getLastPathComponent();
        boolean editGrup = !nodeSel.isRoot();
        jbEditGrup.setEnabled(editGrup);
        jbEditConsulta.setEnabled(editGrup);
        jbNewConsulta.setEnabled(editGrup);
        jbRefreshConsultas.setEnabled(editGrup);
        try {
            cargaBDatos();
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar datos: "
                    + ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void cargaBDatos() throws LBU_Exception {
        TreePath selPath = jTree1.getSelectionPath();
        if (selPath == null) {
            cargaBDatos(-1);
        } else {
            DefaultMutableTreeNode nodeSel = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            if (nodeSel == null) {
                cargaBDatos(-1);
            } else if (!nodeSel.isRoot()) {
                LBE_Grupo grupo = (LBE_Grupo) nodeSel.getUserObject();
                cargaBDatos(grupo.getId());
            } else {
                cargaBDatos(-1);
            }
        }

    }

    private void cargaBDatos(int codigo) throws LBU_Exception {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int numRows = model.getRowCount();
        for (int i = numRows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        LBU_Grupo objBU = new LBU_Grupo(Constantes.UsuarioLogin.getBDatos());
        for (LBE_Consulta elem : objBU.getConsultas(codigo)) {
            Vector row = new Vector();
            row.add(elem.getId());
            row.add(elem.getTitulo());
            row.add(elem.getBe_BDatos().getNombre());
            model.addRow(row);
        }
    }
    private void jbEditGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditGrupActionPerformed
        // TODO add your handling code here:
        TreePath selPath = jTree1.getSelectionPath();
        DefaultMutableTreeNode nodeSel = (DefaultMutableTreeNode) selPath.getLastPathComponent();
        if (!nodeSel.isRoot()) {
            LBE_Grupo elem = (LBE_Grupo) nodeSel.getUserObject();
            jdMttoGrupo frmGrupo = new jdMttoGrupo(null, true, elem.getId());
            frmGrupo.setLocationRelativeTo(this);
            frmGrupo.setVisible(true);
            if (!frmGrupo.isCancelar()) {
                cargaGrupos();
            }
        }

    }//GEN-LAST:event_jbEditGrupActionPerformed

    private void jbRefreshConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshConsultasActionPerformed
        try {
            // TODO add your handling code here:
            cargaBDatos();
        } catch (LBU_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar Base de Datos: "
                    + ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jbRefreshConsultasActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
//            TreePath selPath = jTree1.getSelectionPath();
//            DefaultMutableTreeNode nodeSel = (DefaultMutableTreeNode) selPath.getLastPathComponent();
//            try {
//                if (!nodeSel.isRoot()) {
//                    BE_Grupo grupo = (BE_Grupo) nodeSel.getUserObject();
//                    cargaBDatos(grupo.getId());
//                } else {
//                    cargaBDatos(0);
//                }
//            } catch (BU_Exception ex) {
//                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void jbNewConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewConsultaActionPerformed
        // TODO add your handling code here:
        TreePath selPath = jTree1.getSelectionPath();
        int idGrupo=0;
        if (selPath == null) {
            idGrupo=0;
        } else {
            DefaultMutableTreeNode nodeSel = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            if (nodeSel == null) {
                idGrupo=0;
            } else if (!nodeSel.isRoot()) {
                LBE_Grupo grupo = (LBE_Grupo) nodeSel.getUserObject();
                idGrupo=grupo.getId();
            } else {
                idGrupo=0;
            }
        }

        jdMttoConsulta frmCons = new jdMttoConsulta(null, true, 0,idGrupo);
        frmCons.setLocationRelativeTo(this);
        frmCons.setVisible(true);
        if (!frmCons.isCancelar()) {
            try {
                cargaBDatos();
            } catch (LBU_Exception ex) {
                JOptionPane.showMessageDialog(frmCons, "Error al cargar BDatos ",
                        "Error", JOptionPane.WARNING_MESSAGE);
            }
        }


    }//GEN-LAST:event_jbNewConsultaActionPerformed
    private void editar() {
        int numRow = jTable1.getSelectedRow();
        if (numRow > -1) {
            Integer id = (Integer) jTable1.getValueAt(numRow, 0);
            jdMttoConsulta frmCons = new jdMttoConsulta(null, true, id);
            frmCons.setLocationRelativeTo(this);
            frmCons.setVisible(true);
            if (!frmCons.isCancelar()) {
                try {
                    cargaBDatos();
                } catch (LBU_Exception ex) {
                    JOptionPane.showMessageDialog(frmCons, "Error al cargar consulta ",
                            "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe seleccionar una registro", "Consulta",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void jbEditConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditConsultaActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_jbEditConsultaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            editar();
        }

    }//GEN-LAST:event_jTable1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jbEditConsulta;
    private javax.swing.JButton jbEditGrup;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbNewConsulta;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbRefreshConsultas;
    private javax.swing.JButton jbtExit;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JPanel jpMain;
    // End of variables declaration//GEN-END:variables
}
