CREATE TABLE BASEDATOS
(
    NUM_BASEDATOS       NUMBER  (8,0)
   ,NOM_BASEDATOS       VARCHAR2(150)
   ,GLS_CONEXION        VARCHAR2(150)
   ,GLS_FORMATO_FECHA   VARCHAR2(18)
   ,USER_CONEXION       VARCHAR2(50)
   ,PASS_CONEXION       VARCHAR2(50)
   ,NUM_DRIVER          NUMBER  (6,0)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE BASEDATOS
    ADD CONSTRAINT BDAT_PK PRIMARY KEY(NUM_BASEDATOS)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE BASEDATOS
    ADD CONSTRAINT BDAT_UK UNIQUE (NOM_BASEDATOS)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX BDAT_DRVR_FK ON BASEDATOS
(
    NUM_DRIVER
)
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE BASEDATOS_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
