CREATE TABLE CONSULTAS
(
    NUM_CONSULTA            NUMBER(8,0)
   ,NOM_CONSULTA            VARCHAR2(150)
   ,NUM_BASEDATOS           NUMBER(8,0)
   ,GLS_QUERY               VARCHAR2(4000)
   ,NOM_DUENO               VARCHAR2(50)
   ,NOM_CREADOR             VARCHAR2(50)
   ,FEC_CREACION            TIMESTAMP
   ,FEC_ULT_ACTUALIZACION   TIMESTAMP
   ,GLS_HORARIO_EJECUCION   VARCHAR2(200)
   ,GLS_ARCHIVO_SALIDA      VARCHAR2(250)
   ,NOM_HOJA_SALIDA         VARCHAR2(60)
   ,NUM_AREA                NUMBER(3,0)
   ,NUM_NEGOCIO             NUMBER(3,0)
   ,IND_BLOQUEADA           NUMBER(1,0)
   ,TIPO_CONSULTA           VARCHAR2(20)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE CONSULTAS
    ADD CONSTRAINT CONS_PK PRIMARY KEY(NUM_CONSULTA)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE CONSULTAS
    ADD CONSTRAINT CONS_UK UNIQUE (NOM_CONSULTA)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_TIPO_I ON CONSULTAS
(
    TIPO_CONSULTA
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_VIGE_I ON CONSULTAS
(
    IND_BLOQUEADA
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_DUEN_FK ON CONSULTAS
(
    NOM_DUENO
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_CREA_FK ON CONSULTAS
(
    NOM_CREADOR
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE CONSULTAS_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
