CREATE TABLE CONS_USUARIO
(
    NOM_USUARIO     VARCHAR2(50)
   ,NUM_CONSULTA    NUMBER(8,0)
   ,NOM_CREADOR     VARCHAR2(50)
   ,FEC_CREACION    TIMESTAMP
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE CONS_USUARIO
    ADD CONSTRAINT COUS_PK PRIMARY KEY (NOM_USUARIO, NUM_CONSULTA)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX COUS_CONS_FK ON CONS_USUARIO
(
    NUM_CONSULTA
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX COUS_USUA_FK ON CONS_USUARIO
(
    NOM_USUARIO
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX COUS_CREA_FK ON CONS_USUARIO
(
    NOM_CREADOR
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;
