CREATE TABLE DRIVER
(
    NUM_DRIVER      NUMBER  (3,0)
   ,NOM_DRIVER      VARCHAR2(20)
   ,CLASS_DRIVER    VARCHAR2(150)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE DRIVER
    ADD CONSTRAINT DRVR_PK PRIMARY KEY(NUM_DRIVER)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE DRIVER
    ADD CONSTRAINT DRVR_UK UNIQUE (NOM_DRIVER)
    USING INDEX TABLESPACE SATE_DATA_IDX
;
