CREATE TABLE PARAMETROS
(
    NUM_CONSULTA        NUMBER(8,0)
   ,NOM_PARAMETRO       VARCHAR2(50)
   ,COD_TIPO_DATO       VARCHAR2(20)
   ,COD_TIPO_AYUDA      VARCHAR2(20)
   ,GLS_AYUDA_VALORES   VARCHAR2(4000)
   ,IND_OPCIONAL        NUMBER(1,0)
   ,GLS_PARAMETRO       VARCHAR2(150)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE PARAMETROS
    ADD CONSTRAINT PARM_PK PRIMARY KEY (NUM_CONSULTA,NOM_PARAMETRO)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX PARM_CONS_FK ON PARAMETROS
(
    NUM_CONSULTA
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE PARAMETROS_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
