CREATE TABLE SAT_CONS
(
    CONS_ID         NUMBER(8,0)
   ,CONS_NOMB       VARCHAR2(150)
   ,CONS_SQL        VARCHAR2(4000)
   ,CONS_TIPO       VARCHAR(20)
   ,CONS_HORA       VARCHAR(200)
   ,CONS_VIGE       NUMBER(1,0)
   ,DUEN_USUA_ID    NUMBER(6,0)
   ,CREA_USUA_ID    NUMBER(6,0)
   ,CONX_ID         NUMBER(6,0)
   ,AUDI_CREA       TIMESTAMP
   ,AUDI_MODF       TIMESTAMP
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_CONS
    ADD CONSTRAINT CONS_PK PRIMARY KEY(CONS_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE SAT_CONS
    ADD CONSTRAINT CONS_UK UNIQUE (CONS_NOMB)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_TIPO_I ON SAT_CONS
(
    CONS_TIPO
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_VIGE_I ON SAT_CONS
(
    CONS_VIGE
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_DUEN_FK ON SAT_CONS
(
    DUEN_USUA_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONS_CREA_FK ON SAT_CONS
(
    CREA_USUA_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE SAT_CONS_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
