CREATE TABLE SAT_CONX
(
    CONX_ID     NUMBER  (8,0)
   ,CONX_NOMB   VARCHAR2(150)   
   ,CONX_URL    VARCHAR2(150)
   ,CONX_USER   VARCHAR2(50)
   ,CONX_PASS   VARCHAR2(50)
   ,DRVR_ID     NUMBER  (6,0)
   ,AUDI_CREA   TIMESTAMP DEFAULT SYSTIMESTAMP
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_CONX
    ADD CONSTRAINT CONX_PK PRIMARY KEY(CONX_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE SAT_CONX
    ADD CONSTRAINT CONX_UK UNIQUE (CONX_NOMB)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX CONX_DRVR_FK ON SAT_CONX
(
    DRVR_ID
)
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE SAT_CONX_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
