CREATE TABLE SAT_USUA
(
    USUA_ID     NUMBER(8,0)
   ,USUA_LOGI   VARCHAR2(50)
   ,USUA_NOMB   VARCHAR2(150)
   ,USUA_VIGE   NUMBER(1,0)
   ,TUSU_ID     NUMBER(2,0)
   ,AUDI_CREA   TIMESTAMP
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_USUA
    ADD CONSTRAINT USUA_PK PRIMARY KEY (USUA_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE SAT_USUA
    ADD CONSTRAINT USUA_UK UNIQUE (USUA_LOGI)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX USUA_TUSU_FK ON SAT_USUA
(
    TUSU_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

CREATE INDEX USUA_VIGE_I ON SAT_USUA
(
    USUA_VIGE
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

CREATE SEQUENCE SAT_USUA_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
