CREATE TABLE SAT_DRVR
(
    DRVR_ID     NUMBER  (3,0)
   ,DRVR_NOMB   VARCHAR2(20)
   ,DRVR_CLASS  VARCHAR2(150)
   ,AUDI_CREA   TIMESTAMP DEFAULT SYSTIMESTAMP
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_DRVR
    ADD CONSTRAINT DRVR_PK PRIMARY KEY(DRVR_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE SAT_DRVR
    ADD CONSTRAINT DRVR_UK UNIQUE (DRVR_NOMB)
    USING INDEX TABLESPACE SATE_DATA_IDX
;
