CREATE TABLE SAT_PARM
(
    PARM_ID         NUMBER(8,0)
   ,PARM_NOMB       VARCHAR2(50)
   ,PARM_TEXT       VARCHAR2(150)
   ,PARM_TYPE       VARCHAR2(20)
   ,PARM_AYUD_TIPO  VARCHAR2(20)
   ,PARM_AYUD_VALR  VARCHAR2(4000)
   ,PARM_OPCN       NUMBER(1,0)
   ,CONS_ID         NUMBER(8,0)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_PARM
    ADD CONSTRAINT PARM_PK PRIMARY KEY (PARM_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

ALTER TABLE SAT_PARM
    ADD CONSTRAINT PARM_UK UNIQUE (PARM_NOMB, CONS_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX PARM_CONS_FK ON SAT_PARM
(
    CONS_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_IDX
;

CREATE SEQUENCE SAT_PARM_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
