CREATE TABLE SAT_LOGS
(
    LOGS_ID         NUMBER(20,0)
   ,USUA_ID         NUMBER(8,0)
   ,CONS_ID         NUMBER(8,0)
   ,LOGS_FECH_INI   TIMESTAMP
   ,LOGS_FECH_FIN   TIMESTAMP
   ,LOGS_TMPO       NUMBER(8,0)
   ,LOGS_REGS       NUMBER(8,0)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE SAT_LOGS
    ADD CONSTRAINT LOGS_PK PRIMARY KEY (LOGS_ID)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX LOGS_USUA_FK ON SAT_LOGS
(
    USUA_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

CREATE INDEX LOGS_CONS_FK ON SAT_LOGS
(
    CONS_ID
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;


CREATE SEQUENCE SAT_LOGS_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    ORDER
;
