CREATE TABLE TIPO_USUARIO
(
    COD_TIPO_USUARIO            VARCHAR2(10)
   ,IND_ADMINISTRADOR           VARCHAR2(1)
   ,IND_CREAR_CONSULTAS         VARCHAR2(1)
   ,IND_AUTOASIGNAR_CONSULTAS   VARCHAR2(1)
   ,IND_MODIFICAR_CONSULTAS     VARCHAR2(1)
   ,IND_ELIMINAR_CONSULTAS      VARCHAR2(1)
   ,IND_EJECUTAR_CONSULTAS      VARCHAR2(1)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE TIPO_USUARIO
    ADD CONSTRAINT TUSU_PK PRIMARY KEY(COD_TIPO_USUARIO)
    USING INDEX TABLESPACE SATE_DATA_IDX
;
