CREATE TABLE TIPO_USUARIO
(
    COD_TIPO_USUARIO            VARCHAR2(10)
   ,IND_ADMINISTRADOR           NUMBER(1,0)
   ,IND_CREAR_CONSULTAS         NUMBER(1,0)
   ,IND_AUTOASIGNAR_CONSULTAS   NUMBER(1,0)
   ,IND_MODIFICAR_CONSULTAS     NUMBER(1,0)
   ,IND_ELIMINAR_CONSULTAS      NUMBER(1,0)
   ,IND_EJECUTAR_CONSULTAS      NUMBER(1,0)
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE TIPO_USUARIO
    ADD CONSTRAINT TUSU_PK PRIMARY KEY(COD_TIPO_USUARIO)
    USING INDEX TABLESPACE SATE_DATA_IDX
;
