CREATE TABLE USUARIOS
(
    NOM_USUARIO         VARCHAR2(50)
   ,COD_TIPO_USUARIO    VARCHAR2(10) 
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;

ALTER TABLE USUARIOS
    ADD CONSTRAINT USUA_PK PRIMARY KEY (NOM_USUARIO)
    USING INDEX TABLESPACE SATE_DATA_IDX
;

CREATE INDEX USUA_TUSU_FK ON USUARIOS
(
    COD_TIPO_USUARIO
)
    NOLOGGING
    TABLESPACE SATE_DATA_DAT
;
