CREATE USER SATELITE
    IDENTIFIED BY SATELITE
    DEFAULT TABLESPACE SATE_DATA_DAT
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK    
;

ALTER USER SATELITE
    QUOTA UNLIMITED ON SATE_DATA_DAT
    QUOTA UNLIMITED ON SATE_DATA_IDX
;
    
GRANT CONNECT, RESOURCE TO SATELITE
;
