INSERT INTO TIPO_USUARIO(COD_TIPO_USUARIO, IND_ADMINISTRADOR, IND_CREAR_CONSULTAS, IND_AUTOASIGNAR_CONSULTAS, IND_MODIFICAR_CONSULTAS, IND_ELIMINAR_CONSULTAS, IND_EJECUTAR_CONSULTAS)
    VALUES(1, 1, 1, 0, 1, 1, 1);

INSERT INTO TIPO_USUARIO(COD_TIPO_USUARIO, IND_ADMINISTRADOR, IND_CREAR_CONSULTAS, IND_AUTOASIGNAR_CONSULTAS, IND_MODIFICAR_CONSULTAS, IND_ELIMINAR_CONSULTAS, IND_EJECUTAR_CONSULTAS)
    VALUES(2, 0, 0, 0, 0, 0, 1);
