INSERT INTO DRIVER(NUM_DRIVER, NOM_DRIVER, CLASS_DRIVER)
    VALUES(1, 'ORACLE', 'oracle.jdbc.OracleDriver' );
    
INSERT INTO DRIVER(NUM_DRIVER, NOM_DRIVER, CLASS_DRIVER)
    VALUES(2, 'SQLSERVER', 'com.microsoft.sqlserver.jdbc.SQLServerDriver');
