INSERT INTO SAT_TIPO_USUA(TUSU_ID, TUSU_NOMB, TUSU_ADMN, TUSU_CONS_CREA, TUSU_CONS_AASG, TUSU_CONS_MDIF, TUSU_CONS_ELIM, TUSU_CONS_EJEC)
    VALUES(1, 'ADMIN', 1, 1, 0, 1, 1, 1);

INSERT INTO SAT_TIPO_USUA(TUSU_ID, TUSU_NOMB, TUSU_ADMN, TUSU_CONS_CREA, TUSU_CONS_AASG, TUSU_CONS_MDIF, TUSU_CONS_ELIM, TUSU_CONS_EJEC)
    VALUES(2, 'CONSULTA', 0, 0, 0, 0, 0, 1);
